### ISSUE TITLE
Image built for Dream ONE

### ISSUE THREAD

**Issue by mihaip1948** [atefganm/OpenViX-enigma2#2]
I've build a image for Dream ONE ! following step by step
the instructions ! the result  ....

- during build I had some 4-5 warnings !
- finally the image was build OK
- I've installed into a GPT multiboot
- and does not enter Start Wizard
- a pink Bootlogo is displayed , is trying to start
Enigma 2 then freeze !

**Comment by atefganm** [comment]
Unfortunately, this source does not support dream one and two
Because it is supported, the sound will not work, so what is the point?

**Comment by mihaip1948** [comment]
Thanks ! I've had that suspicion ! but ... what a pleasant wayto learn something ! I've tested all /// OpenATV , OpenPLi (RAED)OpenBH witch is a copy of OpenVIX ! even OpenDreambox ( no build ) !Is there 2 images OpenBH ... 5.1 and 5,2 witch have audio !I must admit ,... in a well guarded secret ! as you saying ... why ?what's the point ! Except OpenATV , the OpenPLi (RAED ) worksalmost well !!! no audio also !
    Pe duminică, 10 decembrie 2023 la 11:29:53 EET, Atef ***@***.***> a scris:  
 
 


Unfortunately, this source does not support dreams one and two
Because it is supported, the sound will not work, so what is the point?
